name: hello world

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: build app
        run: echo "build app"

      - name: test
        run: echo "test app"

      - name: deploy
        run: echo "deploy app"